# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# This workflow deploys the frontend application to Azure App Service.

name: Frontend Deployment

on:
  push:
    branches:
      # Automatically trigger for any branch push except main (for DEV deployment)
      - '*'.!main
  pull_request:
    branches:
      # Automatically trigger for pull requests to main (for UAT deployment)
      - main
  workflow_dispatch:
    # Allow manual triggering of the workflow

env:
  AZURE_RESOURCE_GROUP: BCSAI2024-DEVOPS-STUDENTS-A-UAT # Your specific resource group name
  # User alias is used in Bicep, workflow uses specific app names derived from it

jobs:
  build-and-deploy-dev:
    # This job builds and deploys the frontend to the Development environment
    name: Build and Deploy to DEV
    runs-on: ubuntu-latest
    # Only run this job on push events to non-main branches
    if: github.event_name == 'push' && github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Use a supported Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./ie-bank-fe-2024

      - name: Build frontend
        run: npm run build
        working-directory: ./ie-bank-fe-2024

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (DEV)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jserrano-iebank-dev-fe' # Frontend App Service name for DEV
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          package: ./ie-bank-fe-2024/dist # Package the built frontend code

  build-and-deploy-uat:
    # This job builds and deploys the frontend to the User Acceptance Testing environment
    name: Build and Deploy to UAT
    runs-on: ubuntu-latest
    # Only run this job on pull request events to the main branch
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
    environment:
      name: 'UAT' # Optional: specify an environment in GitHub for protection rules

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Use a supported Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./ie-bank-fe-2024

      - name: Build frontend
        run: npm run build
        working-directory: ./ie-bank-fe-2024

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (UAT)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jserrano-iebank-uat-fe' # Frontend App Service name for UAT
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          package: ./ie-bank-fe-2024/dist # Package the built frontend code
